"""Master composer for card stack JavaScript. Combines viewport height,
scroll navigation, touch navigation, page navigation,
width/scale/count management, and the master HTMX coordinator into a
single namespaced IIFE."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/js/core.ipynb.

# %% auto #0
__all__ = ['global_callback_name', 'generate_card_stack_js']

# %% ../../nbs/js/core.ipynb #jc000003
from typing import Any, Optional, Tuple

from fasthtml.common import Script

from ..core.config import CardStackConfig
from ..core.html_ids import CardStackHtmlIds
from ..core.button_ids import CardStackButtonIds
from ..core.models import CardStackUrls, CardStackState
from cjm_fasthtml_card_stack.core.constants import (
    width_storage_key, scale_storage_key, card_count_storage_key,
    auto_count_storage_key,
    DEFAULT_CARD_WIDTH, DEFAULT_CARD_SCALE, DEFAULT_VISIBLE_COUNT,
)
from .viewport import generate_viewport_height_js
from .scroll import generate_scroll_nav_js
from .touch import generate_touch_nav_js
from .navigation import generate_page_nav_js
from cjm_fasthtml_card_stack.js.controls import (
    _generate_width_mgmt_js, _generate_scale_mgmt_js, _generate_card_count_mgmt_js,
)
from .auto_adjust import _generate_auto_adjust_js

from cjm_fasthtml_virtual_scrollbar.core.models import ScrollbarIds
from cjm_fasthtml_virtual_scrollbar.js.scrollbar import generate_scrollbar_js as _sb_generate_scrollbar_js

# %% ../../nbs/js/core.ipynb #jc000009
def _generate_coordinator_js(
    ids: CardStackHtmlIds,  # HTML IDs for this instance
    config: CardStackConfig,  # Config for prefix-unique listener guards
    button_ids: CardStackButtonIds,  # Nav button IDs (for boundary-no-op guard)
    focus_position: Optional[int] = None,  # Focus slot offset (None=center, -1=bottom, 0=top)
) -> str:  # JS code fragment for master coordinator
    """Generate JS for the master coordinator and HTMX listener."""
    handler_key = f"_csHandlers_{config.prefix.replace('-', '_')}"
    js_focus_pos = "null" if focus_position is None else str(focus_position)
    return f"""
        // === Grid Template Management ===
        ns.applyGridTemplate = function() {{
            const inner = document.getElementById('{ids.card_stack_inner}');
            if (!inner) return;
            const focusPosRaw = {js_focus_pos};
            let tmpl;
            if (focusPosRaw === null) {{
                tmpl = '1fr auto 1fr';
            }} else if (focusPosRaw === 0) {{
                tmpl = 'auto 1fr';
            }} else if (focusPosRaw < 0) {{
                tmpl = '1fr auto';
            }} else {{
                tmpl = '1fr auto 1fr';
            }}
            inner.style.gridTemplateRows = tmpl;
        }};

        // === Focused Section Constraint ===
        // Caps the focused section's max-height to prevent oversized cards
        // from overflowing the grid. Combined with overflow-y-auto on the
        // focused section CSS, this enables scrolling when a card's content
        // exceeds the available viewport height.
        //
        // Also toggles touch-action on the focused section:
        // - No overflow (normal cards): touch-action: none — custom touch nav
        // - Overflow (oversized cards): touch-action: pan-y — native scrolling
        // touch-action is per-section (not on outer container) so the
        // before/after sections always use custom touch nav.
        //
        // The overflow check is synchronous (forced reflow via offsetHeight)
        // to ensure correct results regardless of which navigation path
        // triggered the update (arrow keys, page nav, scrollbar, etc.).
        ns.constrainFocusedSection = function() {{
            const inner = document.getElementById('{ids.card_stack_inner}');
            const focused = document.getElementById('{ids.viewport_section_focused}');
            if (!inner || !focused) return;
            const gap = parseFloat(getComputedStyle(inner).rowGap) || 0;
            const maxH = inner.clientHeight - 2 * gap;
            if (maxH > 0) focused.style.maxHeight = maxH + 'px';

            // Force reflow so scrollHeight/clientHeight reflect the new maxHeight
            focused.offsetHeight;
            focused.style.touchAction = focused.scrollHeight > focused.clientHeight ? 'pan-y' : 'none';
        }};

        // === Boundary Index Helpers ===
        // Read live focused index + total from the focused_index_input hidden input.
        // This input is OOB-swapped on every navigation (via render_focus_oob) and
        // carries both `value` (focused_index) and `data-total-items` — making it
        // the single always-fresh source of truth for boundary checks. Reading from
        // the card-stack container's data attributes would NOT work here: those
        // attributes are set only on initial render, and the nav response OOB-swaps
        // only the viewport sections, progress, focus input, and scrollbar — never
        // the outer card-stack container. Relying on them produces a stale-at-0 bug
        // that blocks all upward nav and never blocks downward nav at the bottom.
        ns._getFocusedIndex = function() {{
            const input = document.getElementById('{ids.focused_index_input}');
            return input ? parseInt(input.value || '0') : 0;
        }};
        ns._getTotalItems = function() {{
            const input = document.getElementById('{ids.focused_index_input}');
            return input ? parseInt(input.dataset.totalItems || '0') : 0;
        }};

        // Buttons whose click would move the focus UP (or to the first item).
        // If focused index is already 0, navigation is a no-op and the HTMX
        // request is canceled before it fires.
        const _UP_BTN_IDS = new Set([
            '{button_ids.nav_up}',
            '{button_ids.nav_page_up}',
            '{button_ids.nav_first}',
        ]);
        // Buttons whose click would move the focus DOWN (or to the last item).
        // If focused index is already total-1, navigation is a no-op.
        const _DOWN_BTN_IDS = new Set([
            '{button_ids.nav_down}',
            '{button_ids.nav_page_down}',
            '{button_ids.nav_last}',
        ]);

        // === Master Coordinator ===
        ns.applyAllViewportSettings = function() {{
            requestAnimationFrame(function() {{
                if (ns.applyWidth) ns.applyWidth();
                if (ns.applyScale) ns.applyScale();
                if (ns.applyGridTemplate) ns.applyGridTemplate();
                if (ns.recalculateHeight) ns.recalculateHeight();
                if (ns.constrainFocusedSection) ns.constrainFocusedSection();
                if (ns._setupSiblingObserver) ns._setupSiblingObserver();

                if (ns._setupScrollNav) ns._setupScrollNav();
                if (ns._setupTouchNav) ns._setupTouchNav();

                requestAnimationFrame(function() {{
                    const cs2 = document.getElementById('{ids.card_stack}');
                    if (cs2) cs2.style.opacity = '1';

                    // Continue auto-adjust loop if an adjustment is in flight
                    if (typeof _autoAdjusting !== 'undefined' && _autoAdjusting) {{
                        _autoAdjusting = false;
                        requestAnimationFrame(function() {{
                            if (ns._runAutoAdjust) ns._runAutoAdjust();
                        }});
                    }}
                }});
            }});
        }};

        // === HTMX Event Listeners ===
        // Remove old listeners from previous IIFE (handles HTMX page navigation
        // that re-executes this script without a full page reload).
        if (window.{handler_key}) {{
            document.body.removeEventListener('htmx:beforeRequest', window.{handler_key}.beforeRequest);
            document.body.removeEventListener('htmx:afterSwap', window.{handler_key}.swap);
            document.body.removeEventListener('htmx:afterSettle', window.{handler_key}.settle);
        }}

        // Boundary no-op guard: cancel nav requests when already at the boundary.
        // Covers both HTMX-triggered (ArrowUp/Down) and JS-callback (page/first/last)
        // paths uniformly — all ultimately fire HTMX from a known nav button.
        function _beforeRequestHandler(evt) {{
            const elt = evt.detail.elt;
            if (!elt || !elt.id) return;
            const idx = ns._getFocusedIndex();
            const total = ns._getTotalItems();
            if (_UP_BTN_IDS.has(elt.id) && idx <= 0) {{
                evt.preventDefault();
                return;
            }}
            if (_DOWN_BTN_IDS.has(elt.id) && total > 0 && idx >= total - 1) {{
                evt.preventDefault();
                return;
            }}
        }}

        function _afterSwapHandler(evt) {{
            const target = evt.detail.target;
            if (!target) return;
            const cs = document.getElementById('{ids.card_stack}');
            const isCSSwap = (
                target.id === '{ids.card_stack}' ||
                target.id === '{ids.card_stack_inner}' ||
                (cs && cs.contains(target))
            );
            if (isCSSwap && typeof _autoGrowing !== 'undefined' && _autoGrowing) {{
                _hideNewItems();
            }}
        }}

        function _afterSettleHandler(evt) {{
            const target = evt.detail.target;
            if (!target) return;
            const cs = document.getElementById('{ids.card_stack}');
            const isCSSwap = (
                target.id === '{ids.card_stack}' ||
                target.id === '{ids.card_stack_inner}' ||
                (cs && cs.contains(target))
            );
            if (isCSSwap) {{
                _syncCountDropdown();
                ns.applyAllViewportSettings();
            }}
            // Always constrain focused section on any settle event.
            // Navigation may be triggered from outside the card stack
            // (page nav buttons, scrollbar) where afterSettle target is
            // the external trigger element, not the OOB sections inside
            // the card stack. constrainFocusedSection is cheap and
            // idempotent — a duplicate call (when isCSSwap is true) is
            // harmless since applyAllViewportSettings already calls it.
            if (ns.constrainFocusedSection) ns.constrainFocusedSection();
        }}

        window.{handler_key} = {{
            beforeRequest: _beforeRequestHandler,
            swap: _afterSwapHandler,
            settle: _afterSettleHandler,
        }};
        document.body.addEventListener('htmx:beforeRequest', _beforeRequestHandler);
        document.body.addEventListener('htmx:afterSwap', _afterSwapHandler);
        document.body.addEventListener('htmx:afterSettle', _afterSettleHandler);

        // === Initialize ===
        requestAnimationFrame(function() {{
            _syncCountDropdown();
            setTimeout(function() {{
                ns.applyAllViewportSettings();
                // Trigger auto-adjust after initial layout settles
                if (ns.triggerAutoAdjust) ns.triggerAutoAdjust();
            }}, 50);
        }});
    """

# %% ../../nbs/js/core.ipynb #jhgisn5noqk
# Callback name constants — must match what create_card_stack_nav_actions uses
_GLOBAL_CALLBACKS = (
    "jumpPageUp",
    "jumpPageDown",
    "jumpToFirstItem",
    "jumpToLastItem",
    "decreaseWidth",
    "increaseWidth",
    "decreaseScale",
    "increaseScale",
)

def global_callback_name(
    prefix: str,  # Card stack instance prefix
    callback: str,  # Base callback name (e.g., "jumpPageUp")
) -> str:  # Global function name (e.g., "cs0_jumpPageUp")
    """Generate a prefix-unique global callback name for keyboard navigation."""
    return f"{prefix}_{callback}"

def _generate_global_callbacks_js(
    config: CardStackConfig,  # Config with prefix
) -> str:  # JS code fragment registering global wrappers
    """Register global wrappers for keyboard navigation system."""
    lines = ["        // === Global Keyboard Callbacks ==="]
    for cb in _GLOBAL_CALLBACKS:
        global_name = global_callback_name(config.prefix, cb)
        lines.append(f"        window['{global_name}'] = function() {{ if (ns.{cb}) ns.{cb}(); }};")
    return "\n".join(lines)

# %% ../../nbs/js/core.ipynb #jc000011
def generate_card_stack_js(
    ids: CardStackHtmlIds,  # HTML IDs for this instance
    button_ids: CardStackButtonIds,  # Button IDs for keyboard triggers
    config: CardStackConfig,  # Card stack configuration
    urls: CardStackUrls,  # URL bundle for routing
    container_id: str = "",  # Consumer's parent container ID (for height calc)
    extra_scripts: Tuple[str, ...] = (),  # Additional JS to include in the IIFE
    focus_position: Optional[int] = None,  # Focus slot offset (None=center, -1=bottom, 0=top)
) -> Any:  # Script element with all card stack JavaScript
    """Compose all card stack JS into a single namespaced IIFE."""
    prefix = config.prefix
    extra_js = "\n".join(extra_scripts)

    # The card stack ID doubles as the keyboard zone ID
    zone_id = ids.card_stack

    # Collect all fragments
    viewport_js = generate_viewport_height_js(ids, container_id)
    scroll_js = generate_scroll_nav_js(ids, button_ids, config.disable_scroll_in_modes, zone_id=zone_id)
    touch_js = generate_touch_nav_js(ids, button_ids, config.disable_scroll_in_modes, zone_id=zone_id)
    page_nav_js = generate_page_nav_js(button_ids)
    width_js = _generate_width_mgmt_js(ids, config, urls)
    scale_js = _generate_scale_mgmt_js(ids, config, urls)
    count_js = _generate_card_count_mgmt_js(ids, config, urls)
    auto_js = _generate_auto_adjust_js(ids, config, urls, focus_position)
    global_cbs_js = _generate_global_callbacks_js(config)
    coordinator_js = _generate_coordinator_js(ids, config, button_ids, focus_position)

    # Scrollbar JS (separate IIFE, runs after the main card stack IIFE)
    scrollbar_js = ""
    if config.show_scrollbar:
        sb_ids = ScrollbarIds(prefix=prefix)
        # Zone activation callback: activates this card stack's keyboard zone on scrollbar interaction
        sb_on_interact = f"_cs_{prefix.replace('-', '_')}_scrollbarActivate"
        scrollbar_js = f"""
        window['{sb_on_interact}'] = function() {{
            if (window.kbNav && window.kbNav.setActiveZone) window.kbNav.setActiveZone('{zone_id}');
        }};
        """ + _sb_generate_scrollbar_js(
            ids=sb_ids,
            position_input_id=ids.focused_index_input,
            nav_url=urls.nav_to_index,
            nav_param="target_index",
            on_interact=sb_on_interact,
        )

    return Script(f"""(function() {{
        window.cardStacks = window.cardStacks || {{}};
        const ns = window.cardStacks['{prefix}'] = {{}};

        {viewport_js}
        {scroll_js}
        {touch_js}
        {page_nav_js}
        {width_js}
        {scale_js}
        {count_js}
        {auto_js}
        {global_cbs_js}
        {coordinator_js}
        {extra_js}
    }})();
    {scrollbar_js}""")
