"""JavaScript generator for scroll-to-nav conversion."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/js/scroll.ipynb.

# %% auto #0
__all__ = ['generate_scroll_nav_js']

# %% ../../nbs/js/scroll.ipynb #js000003
from typing import Tuple

from ..core.html_ids import CardStackHtmlIds
from ..core.button_ids import CardStackButtonIds
from ..core.constants import SCROLL_THRESHOLD, NAVIGATION_COOLDOWN

# %% ../../nbs/js/scroll.ipynb #js000005
def generate_scroll_nav_js(
    ids: CardStackHtmlIds,  # HTML IDs for this card stack instance
    button_ids: CardStackButtonIds,  # Button IDs for navigation triggers
    disable_in_modes: Tuple[str, ...] = (),  # Mode names where scroll nav is suppressed
) -> str:  # JavaScript code fragment for scroll navigation
    """Generate JS for scroll wheel to navigation conversion."""
    # Build mode check
    if disable_in_modes:
        modes_array = ', '.join(f"'{m}'" for m in disable_in_modes)
        mode_check = f"""
        function isScrollDisabled() {{
            if (typeof window.kbNav !== 'undefined') {{
                const state = window.kbNav.getState();
                const disabledModes = [{modes_array}];
                return state && disabledModes.includes(state.currentMode);
            }}
            return false;
        }}
        """
        mode_guard = "if (isScrollDisabled()) return;"
    else:
        mode_check = ""
        mode_guard = ""

    return f"""
        // === Scroll Navigation ===
        const _scrollState = {{ accumulatedDelta: 0, lastNavTime: 0 }};
        const _SCROLL_THRESHOLD = {SCROLL_THRESHOLD};
        const _NAV_COOLDOWN = {NAVIGATION_COOLDOWN};
        {mode_check}
        function setupScrollNavigation() {{
            const cardStack = document.getElementById('{ids.card_stack}');
            if (!cardStack || cardStack._scrollNavSetup) return;
            cardStack._scrollNavSetup = true;

            cardStack.addEventListener('wheel', function(evt) {{
                {mode_guard}
                evt.preventDefault();

                const now = Date.now();
                if (now - _scrollState.lastNavTime > _NAV_COOLDOWN * 2) {{
                    _scrollState.accumulatedDelta = 0;
                }}
                _scrollState.accumulatedDelta += evt.deltaY;

                if (Math.abs(_scrollState.accumulatedDelta) >= _SCROLL_THRESHOLD) {{
                    if (now - _scrollState.lastNavTime >= _NAV_COOLDOWN) {{
                        const btnId = _scrollState.accumulatedDelta > 0
                            ? '{button_ids.nav_down}' : '{button_ids.nav_up}';
                        _scrollState.accumulatedDelta = 0;
                        _scrollState.lastNavTime = now;
                        const btn = document.getElementById(btnId);
                        if (btn) btn.click();
                    }}
                }}
            }}, {{ passive: false }});
        }}

        // Expose for master coordinator to re-setup after swaps
        ns._setupScrollNav = setupScrollNavigation;
    """
