"""JavaScript generator for dynamic viewport height calculation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/js/viewport.ipynb.

# %% auto #0
__all__ = ['generate_viewport_height_js']

# %% ../../nbs/js/viewport.ipynb #jv000003
from ..core.html_ids import CardStackHtmlIds

# %% ../../nbs/js/viewport.ipynb #jv000005
def generate_viewport_height_js(
    ids: CardStackHtmlIds,  # HTML IDs for this card stack instance
    container_id: str = "",  # Consumer's parent container ID (empty = use card stack parent)
) -> str:  # JavaScript code fragment for viewport height calculation
    """Generate JS for dynamic viewport height calculation."""
    # If no container_id, use the card stack's parent element
    container_selector = (
        f"document.getElementById('{container_id}')"
        if container_id
        else f"document.getElementById('{ids.card_stack}').parentElement"
    )

    return f"""
        // === Viewport Height Calculation ===

        function isNonVisualElement(el) {{
            if (!el || el.nodeType !== Node.ELEMENT_NODE) return true;
            const tag = el.tagName;
            if (tag === 'SCRIPT' || tag === 'STYLE') return true;
            if (tag === 'INPUT' && el.type === 'hidden') return true;
            const styles = getComputedStyle(el);
            if (styles.display === 'none') return true;
            return false;
        }}

        function getElementOuterHeight(el) {{
            if (isNonVisualElement(el)) return 0;
            const styles = getComputedStyle(el);
            const marginTop = parseFloat(styles.marginTop) || 0;
            const marginBottom = parseFloat(styles.marginBottom) || 0;
            return el.getBoundingClientRect().height + marginTop + marginBottom;
        }}

        function calculateSpaceBelowContainer(container) {{
            let spaceUsedBelow = 0;
            let currentElement = container;
            let parent = container.parentElement;
            while (parent && parent !== document.body && parent !== document.documentElement) {{
                const parentStyles = getComputedStyle(parent);
                spaceUsedBelow += parseFloat(parentStyles.paddingBottom) || 0;
                let foundCurrent = false;
                for (const sibling of parent.children) {{
                    if (sibling === currentElement) {{ foundCurrent = true; continue; }}
                    if (!foundCurrent) continue;
                    spaceUsedBelow += getElementOuterHeight(sibling);
                }}
                currentElement = parent;
                parent = parent.parentElement;
            }}
            return spaceUsedBelow;
        }}

        function calculateSiblingHeight(container, excludeId) {{
            let height = 0;
            for (const child of container.children) {{
                if (child.id === excludeId) continue;
                height += getElementOuterHeight(child);
            }}
            return height;
        }}

        function calculateAndSetViewportHeight() {{
            const container = {container_selector};
            const cardStack = document.getElementById('{ids.card_stack}');
            const cardStackInner = document.getElementById('{ids.card_stack_inner}');
            if (!container || !cardStack) return 400;

            const windowHeight = window.innerHeight;
            const containerTop = container.getBoundingClientRect().top;
            const containerStyles = getComputedStyle(container);
            const containerPadTop = parseFloat(containerStyles.paddingTop) || 0;
            const containerPadBot = parseFloat(containerStyles.paddingBottom) || 0;
            const siblingHeight = calculateSiblingHeight(container, '{ids.card_stack}');
            const spaceBelow = calculateSpaceBelowContainer(container);

            const viewportHeight = Math.max(200,
                windowHeight - containerTop - containerPadTop - containerPadBot
                - siblingHeight - spaceBelow
            );

            cardStack.style.height = viewportHeight + 'px';
            cardStack.style.maxHeight = viewportHeight + 'px';
            cardStack.style.minHeight = viewportHeight + 'px';
            if (cardStackInner) cardStackInner.style.height = viewportHeight + 'px';

            return viewportHeight;
        }}

        function _debounce(fn, delay) {{
            let tid;
            return function(...args) {{ clearTimeout(tid); tid = setTimeout(() => fn.apply(this, args), delay); }};
        }}

        const _debouncedResize = _debounce(calculateAndSetViewportHeight, 100);

        if (!window._csResizeListener_{ids.prefix.replace('-', '_')}) {{
            window._csResizeListener_{ids.prefix.replace('-', '_')} = true;
            window.addEventListener('resize', _debouncedResize);
        }}

        // Expose on namespace
        ns.recalculateHeight = calculateAndSetViewportHeight;
    """
