"""Keyboard navigation focus zone and action factories for the card stack."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/keyboard/actions.ipynb.

# %% auto #0
__all__ = ['create_card_stack_focus_zone', 'create_card_stack_nav_actions']

# %% ../../nbs/keyboard/actions.ipynb #ka000003
from typing import Optional, Tuple

from cjm_fasthtml_keyboard_navigation.core.focus_zone import FocusZone
from cjm_fasthtml_keyboard_navigation.core.actions import KeyAction
from cjm_fasthtml_keyboard_navigation.core.navigation import ScrollOnly

from ..core.config import CardStackConfig
from ..core.html_ids import CardStackHtmlIds
from ..core.button_ids import CardStackButtonIds
from ..js.core import global_callback_name

# %% ../../nbs/keyboard/actions.ipynb #ka000005
def create_card_stack_focus_zone(
    ids: CardStackHtmlIds,  # HTML IDs for this card stack instance
    on_focus_change: Optional[str] = None,  # JS callback name on focus change
    hidden_input_prefix: Optional[str] = None,  # Prefix for keyboard nav hidden inputs
    data_attributes: Tuple[str, ...] = (),  # Data attributes to track on focused items
) -> FocusZone:  # Configured focus zone for the card stack
    """Create a focus zone for a card stack viewport."""
    return FocusZone(
        id=ids.card_stack,
        item_selector="[data-card-role='focused']",
        navigation=ScrollOnly(),
        data_attributes=data_attributes,
        zone_focus_classes=(),
        item_focus_classes=(),
        on_focus_change=on_focus_change or "",
        hidden_input_prefix=hidden_input_prefix or f"{ids.prefix}-focused",
    )

# %% ../../nbs/keyboard/actions.ipynb #ka000010
def create_card_stack_nav_actions(
    zone_id: str,  # Focus zone ID to restrict actions to
    button_ids: CardStackButtonIds,  # Button IDs for HTMX triggers
    config: CardStackConfig,  # Config (for prefix-unique callback names)
    disable_in_modes: Tuple[str, ...] = (),  # Mode names that disable navigation
) -> Tuple[KeyAction, ...]:  # Standard card stack navigation actions
    """Create standard keyboard navigation actions for a card stack."""
    zone_ids = (zone_id,)
    not_modes = disable_in_modes if disable_in_modes else ()
    prefix = config.prefix

    return (
        # --- Item navigation (HTMX triggers) ---
        KeyAction(
            key="ArrowUp",
            htmx_trigger=button_ids.nav_up,
            zone_ids=zone_ids,
            not_modes=not_modes,
            description="Previous item",
            hint_group="Navigation",
        ),
        KeyAction(
            key="ArrowDown",
            htmx_trigger=button_ids.nav_down,
            zone_ids=zone_ids,
            not_modes=not_modes,
            description="Next item",
            hint_group="Navigation",
        ),

        # --- Page jump (JS callbacks, prefix-unique) ---
        KeyAction(
            key="ArrowUp",
            modifiers=frozenset({"ctrl"}),
            js_callback=global_callback_name(prefix, "jumpPageUp"),
            zone_ids=zone_ids,
            not_modes=not_modes,
            description="Page up",
            hint_group="Navigation",
        ),
        KeyAction(
            key="ArrowDown",
            modifiers=frozenset({"ctrl"}),
            js_callback=global_callback_name(prefix, "jumpPageDown"),
            zone_ids=zone_ids,
            not_modes=not_modes,
            description="Page down",
            hint_group="Navigation",
        ),

        # --- First/last item (JS callbacks, prefix-unique) ---
        KeyAction(
            key="ArrowUp",
            modifiers=frozenset({"ctrl", "shift"}),
            js_callback=global_callback_name(prefix, "jumpToFirstItem"),
            zone_ids=zone_ids,
            not_modes=not_modes,
            description="First item",
            hint_group="Navigation",
        ),
        KeyAction(
            key="ArrowDown",
            modifiers=frozenset({"ctrl", "shift"}),
            js_callback=global_callback_name(prefix, "jumpToLastItem"),
            zone_ids=zone_ids,
            not_modes=not_modes,
            description="Last item",
            hint_group="Navigation",
        ),

        # --- Width adjustment (available in any mode) ---
        KeyAction(
            key="[",
            js_callback=global_callback_name(prefix, "decreaseWidth"),
            zone_ids=zone_ids,
            description="Narrower",
            hint_group="View",
        ),
        KeyAction(
            key="]",
            js_callback=global_callback_name(prefix, "increaseWidth"),
            zone_ids=zone_ids,
            description="Wider",
            hint_group="View",
        ),

        # --- Scale adjustment (available in any mode) ---
        KeyAction(
            key="-",
            js_callback=global_callback_name(prefix, "decreaseScale"),
            zone_ids=zone_ids,
            description="Smaller",
            hint_group="View",
        ),
        KeyAction(
            key="=",
            js_callback=global_callback_name(prefix, "increaseScale"),
            zone_ids=zone_ids,
            description="Larger",
            hint_group="View",
        ),
    )
