"""Loading and placeholder card components for the card stack viewport. Empty-state rendering is provided by `cjm-fasthtml-app-core`'s `render_empty_state` (V8 anatomy composition helper) &mdash; card-stack consumers wire that helper into their viewport's empty callback rather than card-stack shipping a local empty-state default."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/states.ipynb.

# %% auto #0
__all__ = ['render_placeholder_card', 'render_loading_state']

# %% ../../nbs/components/states.ipynb #s1000003
from typing import Any, Literal

from fasthtml.common import Div, P, Span

# DaisyUI components
from cjm_fasthtml_daisyui.components.data_display.card import card, card_body
from cjm_fasthtml_daisyui.components.feedback.loading import loading, loading_styles, loading_sizes
from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui, text_dui

from cjm_fasthtml_design_system.text_tiers import text_tiers

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.borders import border, border_color
from cjm_fasthtml_tailwind.utilities.effects import shadow
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, items, justify, grow
)
from cjm_fasthtml_tailwind.utilities.layout import visibility
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w
from cjm_fasthtml_tailwind.utilities.typography import font_size, italic, text_align
from cjm_fasthtml_tailwind.core.base import combine_classes

# Local imports
from ..core.html_ids import CardStackHtmlIds

# %% ../../nbs/components/states.ipynb #s1000005
def render_placeholder_card(
    placeholder_type: Literal["start", "end"],  # Which edge of the list
    show_label: bool = False,                   # Render the "Beginning"/"End" label visibly. Default hides via visibility.invisible (preserves height contract).
) -> Any:  # Placeholder card component
    """Render a placeholder card for viewport edges (fills geometric slot so focus position stays centered)."""
    text = "Beginning" if placeholder_type == "start" else "End"

    text_classes = [font_size.lg, italic, text_tiers.subtle]
    if not show_label:
        text_classes.append(visibility.invisible)

    return Div(
        Div(
            P(
                text,
                cls=combine_classes(*text_classes)
            ),
            cls=combine_classes(card_body, p(3))
        ),
        cls=combine_classes(
            card, "placeholder-card",
            bg_dui.base_100.opacity(50), shadow.none,
            border(2), border_color.transparent
        ),
        data_placeholder_type=placeholder_type
    )

# %% ../../nbs/components/states.ipynb #s1000008
def render_loading_state(
    ids: CardStackHtmlIds,  # HTML IDs for this card stack instance
    message: str = "Loading...",  # Loading message text
) -> Any:  # Loading component
    """Render loading state with spinner and message."""
    return Div(
        Div(
            Span(cls=combine_classes(loading, loading_styles.spinner, loading_sizes.lg)),
            P(
                message,
                cls=combine_classes(m.t(4), text_tiers.tertiary)
            ),
            cls=combine_classes(
                flex_display, flex_direction.col, items.center, justify.center,
                p(16)
            )
        ),
        id=ids.loading
    )
