"""Configuration dataclass for card stack initialization."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/config.ipynb.

# %% auto #0
__all__ = ['CardStackConfig']

# %% ../../nbs/core/config.ipynb #b1000003
from dataclasses import dataclass, field
from typing import Tuple

# %% ../../nbs/core/config.ipynb #b1000005
_prefix_counter: int = 0

def _auto_prefix() -> str:  # Unique prefix string (e.g., "cs0", "cs1")
    """Generate an auto-incrementing unique prefix."""
    global _prefix_counter
    p = f"cs{_prefix_counter}"
    _prefix_counter += 1
    return p

def _reset_prefix_counter() -> None:
    """Reset the prefix counter (for testing only)."""
    global _prefix_counter
    _prefix_counter = 0

# %% ../../nbs/core/config.ipynb #b1000008
@dataclass
class CardStackConfig:
    """Initialization-time settings for a card stack instance."""
    prefix: str = field(default_factory=_auto_prefix)  # HTML ID prefix (auto-generated if omitted)

    # Card count selector options
    visible_count_options: Tuple[int, ...] = (1, 3, 5, 7, 9)  # Choices for card count dropdown
    auto_visible_count: bool = True  # Whether "Auto" option appears in card count dropdown

    # Width slider bounds
    card_width_min: int = 30    # Width slider minimum (rem)
    card_width_max: int = 120   # Width slider maximum (rem)
    card_width_step: int = 5    # Width slider step (rem)

    # Scale slider bounds
    card_scale_min: int = 50    # Scale slider minimum (%)
    card_scale_max: int = 200   # Scale slider maximum (%)
    card_scale_step: int = 10   # Scale slider step (%)

    # Interaction
    click_to_focus: bool = False  # Whether context cards get transparent click overlay
    disable_scroll_in_modes: Tuple[str, ...] = ()  # Mode names where scroll-to-nav is suppressed
